spring.application.name=webapp
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=zafir
spring.datasource.password=

spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB

gearhub.admin.email=admin@gearhub.local
gearhub.admin.password=${GEARHUB_ADMIN_PASSWORD:ChangeMe-Admin1}
gearhub.admin.name=GearHub Admin