CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS gear_listings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT        NOT NULL,
    title           VARCHAR(120)  NOT NULL,
    category        VARCHAR(40)   NOT NULL,
    gear_condition  VARCHAR(10)   NOT NULL,
    daily_rate      DECIMAL(10,2) NOT NULL,
    pickup_suburb   VARCHAR(100)  NOT NULL,
    pickup_postcode CHAR(4)       NOT NULL,
    description     VARCHAR(1000),
    expiry_date     DATE          NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PUBLISHED',
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listing_photos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id    BIGINT       NOT NULL REFERENCES gear_listings(id),
    content_type  VARCHAR(20)  NOT NULL,
    data          BLOB         NOT NULL,
    display_order INT          NOT NULL
);
