CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS gear_listings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT        NOT NULL,
    title           VARCHAR(120)  NOT NULL,
    category        VARCHAR(40)   NOT NULL,
    gear_condition  VARCHAR(10)   NOT NULL,
    daily_rate      DECIMAL(10,2) NOT NULL,
    pickup_suburb   VARCHAR(100)  NOT NULL,
    pickup_postcode CHAR(4)       NOT NULL,
    description     VARCHAR(1000),
    expiry_date     DATE          NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PUBLISHED',
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listing_photos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id    BIGINT       NOT NULL REFERENCES gear_listings(id),
    content_type  VARCHAR(20)  NOT NULL,
    data          BLOB         NOT NULL,
    display_order INT          NOT NULL
);

-- Shared with the Booking & Rental stories (GL-8 to GL-10).
-- Statuses: PENDING, ACCEPTED, DECLINED, CANCELLED, CLOSED (optionally COMPLETED).
-- Reviews treat ACCEPTED/COMPLETED rentals whose end_date has passed as completed.
CREATE TABLE IF NOT EXISTS rental_requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  BIGINT      NOT NULL REFERENCES gear_listings(id),
    renter_id   BIGINT      NOT NULL REFERENCES users(id),
    start_date  DATE        NOT NULL,
    end_date    DATE        NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Reviews and Ratings. One review per (rental, reviewer, type):
--   GEAR   renter -> gear condition   (reviewee = owner, tied to listing)
--   OWNER  renter -> owner reliability
--   RENTER owner  -> renter reliability
CREATE TABLE IF NOT EXISTS reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id   BIGINT        NOT NULL REFERENCES rental_requests(id),
    reviewer_id BIGINT        NOT NULL REFERENCES users(id),
    reviewee_id BIGINT        NOT NULL REFERENCES users(id),
    listing_id  BIGINT        NOT NULL REFERENCES gear_listings(id),
    review_type VARCHAR(10)   NOT NULL,
    rating      INT           NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     VARCHAR(1000),
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_review_per_rental UNIQUE (rental_id, reviewer_id, review_type)
);

-- Admin Tools: audit trail of every moderation action.
CREATE TABLE IF NOT EXISTS admin_actions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    BIGINT       NOT NULL REFERENCES users(id),
    action_type VARCHAR(30)  NOT NULL,
    target_type VARCHAR(10)  NOT NULL,
    target_id   BIGINT       NOT NULL,
    reason      VARCHAR(500) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
